name= "moontv"
compatibility_flags= ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"
#[assets]
#directory  = ".vercel/output/static"

#[vars]
#USERNAME = "jenningsl"
#PASSWORD = "jenningslllooo"
#NEXT_PUBLIC_STORAGE_TYPE = "d1"

#[[d1_databases]]
#binding = "DB"
#database_name = "tvdb"
#database_id = "bf4b1f77-b484-41a7-813c-4b0d4d5975a0"
